package spawnspec

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/invopop/jsonschema"
)

// SpecSchema returns the JSON Schema for SpawnSpec. The Go structs in
// types.go are the source of truth; this is generated by reflection
// over their jsonschema tags so non-Go consumers (TS UI, Python
// validators, IDE plugins) can validate without hand-maintaining a
// parallel schema. The pattern matches Kubernetes/Argo/Tekton: structs
// are canonical, JSON Schema is the published artifact.
//
// Returns indented JSON, ready to write to disk.
func SpecSchema() ([]byte, error) {
	return marshalSchema((*SpawnSpec)(nil), "https://orch.io/schemas/spawn-spec.v1.json", "SpawnSpec v1")
}

// HandleSchema returns the JSON Schema for WorkerHandle.
func HandleSchema() ([]byte, error) {
	return marshalSchema((*WorkerHandle)(nil), "https://orch.io/schemas/worker-handle.v1.json", "WorkerHandle v1")
}

// JSONSchema teaches invopop/jsonschema to emit the closed enum on the
// `agent:` field so non-Go consumers catch unknown values at PARSE
// (proposal 0002 Ousterhout adjustment: define errors out of existence).
// Without this hook the reflector would emit {"type": "string"} only,
// defeating the published-schema contract.
func (Agent) JSONSchema() *jsonschema.Schema {
	enum := make([]any, 0, len(KnownAgents()))
	for _, a := range KnownAgents() {
		enum = append(enum, string(a))
	}
	return &jsonschema.Schema{
		Type: "string",
		Enum: enum,
	}
}

func marshalSchema(zeroValue any, id, title string) ([]byte, error) {
	r := &jsonschema.Reflector{
		// Surface every nested type as a $defs entry — friendlier for
		// IDEs that follow references than inlining everything.
		ExpandedStruct:            false,
		RequiredFromJSONSchemaTags: false,
		DoNotReference:            false,
	}
	schema := r.Reflect(zeroValue)
	schema.ID = jsonschema.ID(id)
	schema.Title = title

	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	if err := enc.Encode(schema); err != nil {
		return nil, fmt.Errorf("spawnspec: schema marshal: %w", err)
	}
	return buf.Bytes(), nil
}
