package spawnspec

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/invopop/jsonschema"
)

// SpecSchema returns the JSON Schema for SpawnSpec. The Go structs in
// types.go are the source of truth; this is generated by reflection
// over their jsonschema tags so non-Go consumers (TS UI, Python
// validators, IDE plugins) can validate without hand-maintaining a
// parallel schema. The pattern matches Kubernetes/Argo/Tekton: structs
// are canonical, JSON Schema is the published artifact.
//
// Returns indented JSON, ready to write to disk.
func SpecSchema() ([]byte, error) {
	return marshalSchema((*SpawnSpec)(nil), "https://orch.io/schemas/spawn-spec.v1.json", "SpawnSpec v1")
}

// HandleSchema returns the JSON Schema for WorkerHandle.
func HandleSchema() ([]byte, error) {
	return marshalSchema((*WorkerHandle)(nil), "https://orch.io/schemas/worker-handle.v1.json", "WorkerHandle v1")
}

func marshalSchema(zeroValue any, id, title string) ([]byte, error) {
	r := &jsonschema.Reflector{
		// Surface every nested type as a $defs entry — friendlier for
		// IDEs that follow references than inlining everything.
		ExpandedStruct:            false,
		RequiredFromJSONSchemaTags: false,
		DoNotReference:            false,
	}
	schema := r.Reflect(zeroValue)
	schema.ID = jsonschema.ID(id)
	schema.Title = title

	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	if err := enc.Encode(schema); err != nil {
		return nil, fmt.Errorf("spawnspec: schema marshal: %w", err)
	}
	return buf.Bytes(), nil
}
