package spawnspec

// SpecSchemaV2 returns the JSON Schema for SpawnSpecV2. Generated by
// reflection over the v2 struct family in types_v2.go. v1's
// SpecSchema continues to reflect the v1 struct family in types.go,
// keeping dist/schema/spawn-spec.v1.json byte-identical.
func SpecSchemaV2() ([]byte, error) {
	return marshalSchema((*SpawnSpecV2)(nil), "https://orch.io/schemas/spawn-spec.v2.json", "SpawnSpec v2")
}

// HandleSchemaV2 returns the JSON Schema for WorkerHandleV2.
func HandleSchemaV2() ([]byte, error) {
	return marshalSchema((*WorkerHandleV2)(nil), "https://orch.io/schemas/worker-handle.v2.json", "WorkerHandle v2")
}
